version: "2"
services:
  app:
    container_name: bubble-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:xenial
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: