apiVersion: v1
kind: Service
metadata:
  name: bubble-api
  namespace: default
  labels:
    app: bubble-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: bubble-api
